### ISSUE TITLE
Infografía Realidad Aumentada

### ISSUE THREAD

**Issue by garaudy12** [SistemasTecTlaxiaco/infografia-garaudy12#1]
[Infografía RA.pdf](https://github.com/SistemasTecTlaxiaco/infografia-garaudy12/files/8126223/Infografia.RA.pdf)

**Comment by Anthony4523** [comment]
Buen trabajo, contiene todos los datos necesarios, la información está organizada y tiene un buen diseño.
Calificación: 20/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado
